const movieStatusMap = {
  1: "both",
  2: "now-showing",
  3: "now-showing",
  4: "now-showing",
  5: "now-showing",
  6: "now-showing",
  7: "now-showing",
  8: "now-showing",
  9: "now-showing",
  10: "now-showing",
  11: "both",
  12: "now-showing",
  13: "upcoming",
  14: "upcoming",
  15: "upcoming",
  16: "upcoming",
  17: "upcoming",
  18: "upcoming",
  19: "upcoming",
  20: "upcoming",
  21: "upcoming",
  22: "upcoming",
  23: "upcoming",
  24: "upcoming",
  25: "upcoming",
  26: "upcoming",
};

module.exports = movieStatusMap;
